name: TypeScript To Lua

on:
  push:
    branches:
    - master
    - main
  pull_request:
    branches:
    - master
    - main

jobs:
  build_artifact:
    runs-on: ubuntu-latest
    name: Build and publish artifact
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up npm
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: Install and run TSTL
      run: |
        npm install
        npm run build
    - name: Publish artifact
      uses: actions/upload-artifact@v4
      with:
        path: main.lua
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    needs:
      build_artifact
    name: Upload release
    steps:
    - name: Get artifact
      uses: actions/download-artifact@v4
    - name: Upload release
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
      run: |
        cd artifact;
        gh release create "$tag" \
          --title="${tag#v}" \
          --generate-notes \
          --fail-on-no-commits \
          main.lua
